name: Build for Github Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run scraper
        run: |
          python scraper.py
      - name: Archive data
        uses: actions/upload-artifact@v2
        with:
          name: scrap_data
          path: |
            vacc_data.csv
      