name: FOPH scraper

on: [workflow_dispatch, push]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          path: 'scraper'
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Run scraper
        run: |
          python scraper/scraper.py
      # - name: Archive data
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: scrap_data
      #     path: |
      #       vacc_data.csv
      
      - name: Checkout fohp-covid19-data
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          repository: 'doerfli/foph-covid19-data'
          path: 'foph-covid19-data'
      - name: Copy data to data repo
        run: |
          cp vacc_data.csv foph-covid19-data
      - name: Commit files
        run: |
          cd foph-covid19-data
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update data" -a
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WRITE_TOKEN }}
          directory: foph-covid19-data
          repository: doerfli/foph-covid19-data
      