name: FOPH scraper

on: 
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 */6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
          path: 'scraper'
      - name: Set up Python 3.x
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Run scraper
        run: |
          python scraper/scraper.py

      - name: Push scraped data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'vacc_data.csv'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main
      
      - name: Push scraped data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'pop.csv'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main

      - name: Push scraped cases data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'cases/'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main
          
      