name: FOPH scraper

on: 
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '3 */4 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: 'scraper'
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Grab dataset.zip.sha256
        uses: wei/wget@v1
        continue-on-error: true
        with:
          args: -O dataset.zip.latest.sha256 https://raw.githubusercontent.com/doerfli/foph-covid19-data/main/dataset.zip.sha256

      - name: Run scraper
        run: |
          python scraper/scraper.py

      - name: Archive scraped data
        uses: actions/upload-artifact@v2
        with:
          name: scrape_data
          path: |
            cases/
            vacc_data/
            vacc_data.csv
            pop.csv
            dataset.zip.sha256
            dataset.zip.latest.sha256

  upload:
    needs: scrape
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download scraped data
        uses: actions/download-artifact@v2
        with:
          name: scrape_data
          path: ./
      - name: Check file dataset.zip.sha256 exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "dataset.zip.sha256"

      - name: Push scraped data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'vacc_data.csv'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main

      - name: Push scraped data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'vacc_data/'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main
      
      - name: Push scraped data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.0
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'pop.csv'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main

      - name: Push scraped cases data to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'cases/'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main
      
      - name: Push dataset checksum to doerfli/foph-covid19-data
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          API_TOKEN_GITHUB: ${{ secrets.WRITE_TOKEN }}
        with:
          source_file: 'dataset.zip.sha256'
          destination_repo: 'doerfli/foph-covid19-data'
          user_email: 'github@doerf.li'
          user_name: 'doerfli'
          destination_branch: main
          
      